# 资源表 obj
# queryRoles addRole 等操作
type Resource {
    _id: ID!
    name: String
}
type Query {
    queryResources: [Resource]
}
type Mutation {
    insertResources: [Resource]
    removeAllResource: String
}