
### 注册请求01
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "name": "任盈盈",
    "email": "ryy@163.com",
    "password": "123"
}
### 注册请求02
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "name": "杨钰莹",
    "email": "yyy@163.com",
    "password": "789"
}
### 注册请求03
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "name": "周芷若",
    "email": "zzr@163.com",
    "password": "456"
}
### 注册请求04
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "name": "赵敏",
    "email": "zm@163.com",
    "password": "123"
}

### 登录请求
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "ryy@163.com",
    "password": "123"
}